############ YAML ANCHORS ############
.preliminaries_template: &preliminaries_definition
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ## Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh  
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  # - echo "$SSH_KNOWN_HOSTS" > $HOME/.ssh/known_hosts
  - ssh-keyscan -H -p 2202 gitlab.iri.upc.edu >> $HOME/.ssh/known_hosts

  # update apt
  - apt-get update

.install_wolf_template: &install_wolf_definition
  - git clone ssh://git@gitlab.iri.upc.edu:2202/mobile_robotics/wolf_projects/wolf_lib/wolf.git
  - cd wolf
  - mkdir -pv build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON ..
  - make -j$(nproc)
  - ctest -j$(nproc)
  - make install
  - cd ../..

.install_visionutils_template: &install_visionutils_definition
  - git clone https://gitlab.iri.upc.edu/labrobotica/algorithms/vision_utils.git
  - cd laser_scan_utils
  - mkdir -pv build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release ..
  - make -j$(nproc)
  - make install
  - cd ../..

.build_and_test_template: &build_and_test_definition
  - mkdir -pv build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON ..
  - make -j$(nproc)
  - ctest -j$(nproc)
  - make install

############ UBUNTU 16.04 TESTS ############
wolf_build_and_test_none:xenial:
  image: labrobotica/wolf_vision_deps:16.04
  except:
    - master
  before_script:
    - *preliminaries_definition
    - *install_wolf_definition
    - *install_visionutils_definition
    - ldconfig # update links (shared libraries)
  script:
    - *build_and_test_definition

############ UBUNTU 18.04 TESTS ############
wolf_build_and_test_none:bionic:
  image: labrobotica/wolf_vision_deps:18.04
  except:
    - master
  before_script:
    - *preliminaries_definition
    - *install_wolf_definition
    - *install_visionutils_definition
    - ldconfig # update links (shared libraries)
  script:
    - *build_and_test_definition