sensor:
  type: "USB_CAM"

detector:
  type: "ORB"         
  nfeatures: 100
  scale factor: 1.2
  nlevels: 8
  edge threshold: 8   # 16
  first level: 0 
  WTA_K: 2            # See: http://docs.opencv.org/trunk/db/d95/classcv_1_1ORB.html#a180ae17d3300cf2c619aa240d9b607e5
  score type: 1       #enum { kBytes = 32, HARRIS_SCORE=0, FAST_SCORE=1 };
  patch size: 15      # 31

descriptor:
  type: "ORB"         
  nfeatures: 100
  scale factor: 1.2
  nlevels: 8
  edge threshold: 8   # 16
  first level: 0 
  WTA_K: 2            # See: http://docs.opencv.org/trunk/db/d95/classcv_1_1ORB.html#a180ae17d3300cf2c619aa240d9b607e5
  score type: 1       #enum { kBytes = 32, HARRIS_SCORE=0, FAST_SCORE=1 };
  patch size: 15      # 31

matcher:
  type: "FLANNBASED"
  match type: 1     #  Match type. MATCH = 1, KNNMATCH = 2, RADIUSMATCH = 3
  roi:
    width: 20
    height: 20
  min normalized score: 0.85 
    
algorithm:
  type: "ACTIVESEARCH"   
  draw results: true
  grid horiz cells: 12
  grid vert cells: 8
  separation: 10
  min features to track: 5
  max new features: 40
  min response new features: 80